// Anciennes URL d'articles WordPress (une page par communiqué / retombée média,
// jamais liée depuis le site mais indexée) → rubrique correspondante.
// Généré par scripts/import à partir de l'export WordPress.
const POSTS: Array<[slug: string, destination: string]> = [
  ["arnaud-molinie-rejoint-le-board-france-delectrip-et-devient-senior-advisor-de-wren-house", "/communiques-de-presse"],
  ["deloitte-enrichit-son-plan-sante-en-incluant-une-nouvelle-offre-de-bilan-de-prevention-en-partenariat-avec-doxamed-29-01-2026", "/communiques-de-presse"],
  ["capitello-group-renforce-son-leadership-en-medtech-avec-lacquisition-de-teledok", "/communiques-de-presse"],
  ["bpifrance-deploie-un-plan-de-sante-incluant-une-offre-de-bilans-de-sante-pour-tous-ses-collaborateurs", "/communiques-de-presse"],
  ["pluxee-elargit-son-offre-dans-le-domaine-de-la-sante-grace-a-un-partenariat-strategique-avec-doxamed", "/communiques-de-presse"],
  ["trois-nominations-au-sein-de-doxamed", "/communiques-de-presse"],
  ["medigo-une-nouvelle-generation-de-cabinets-medicaux-mobiles-connectes-pour-lutter-contre-les-deserts-medicaux", "/communiques-de-presse"],
  ["initiative-inedite-pour-la-sante-au-travail-en-france", "/communiques-de-presse"],
  ["loxamed-devient-doxamed-une-nouvelle-etape-de-son-developpement", "/communiques-de-presse"],
  ["un-vehicule-medical-innovant-pour-aller-au-plus-pres-des-patients-sur-le-territoire-francilien", "/communiques-de-presse"],
  ["un-vehicule-medical-innovant-pour-aller-au-plus-pres-des-patients", "/communiques-de-presse"],
  ["prevention-depistage-telemedecine-la-sante-rentre-en-gare", "/communiques-de-presse"],
  ["loxamed-propose-un-service-rapide-de-conversion-du-pass-vaccinal-aux-normes-europeennes-a-destination-des-francais-de-letranger", "/communiques-de-presse"],
  ["un-dispositif-de-depistage-installe-dans-le-centre-de-shopping-westfiel-parly-2-au-chesnay-rocquencourt", "/communiques-de-presse"],
  ["une-box-mobile-de-depistage-installee-a-versailles", "/communiques-de-presse"],
  ["doxamed-ex-loxamed-vient-en-soutien-des-stations-de-ski-et-installe-un-dispositif-de-depistage-covid-a-chamrousse", "/communiques-de-presse"],
  ["loxamed-installe-un-hub-sanitaire-a-louveciennes", "/communiques-de-presse"],
  ["loxamed-porte-drapeau-de-linnovation-medicale-au-salon-des-maires", "/communiques-de-presse"],
  ["conference-de-presse-presentation-du-dispositif-innovant-mobiltest", "/communiques-de-presse"],
  ["loxamed-en-forte-croissance-se-renforce-et-se-structure-pour-faire-face-aux-nouveaux-defis-sanitaires-qui-sannoncent", "/communiques-de-presse"],
  ["loxamed-sinstalle-dans-11-nouvelles-gares-et-offre-aux-voyageurs-une-solution-de-depistage-rapide", "/communiques-de-presse"],
  ["le-parc-asterix-en-partenariat-avec-loxamed-met-a-disposition-de-ses-visiteurs-un-dispositif-de-depistage-rapide-a-lentree-du-parc", "/communiques-de-presse"],
  ["reouverture-des-etablissements-de-nuit-loxamed-installe-a-la-baule-escoublac-la-premiere-box-de-depistage-contre-la-covid-en-loire-atlantique", "/communiques-de-presse"],
  ["loxamed-se-structure-pour-repondre-aux-defis-sanitaires-de-lindustrie-touristique", "/communiques-de-presse"],
  ["doxamed-avec-son-partenaire-unilabs-france-installe-un-dispositif-unique-de-depistage-immediat-pour-les-personnels-navigants-dair-france", "/communiques-de-presse"],
  ["en-partenariat-avec-sncf-gares-connexions-doxamed-et-les-laboratoires-unilabs-france-installent-une-premiere-box-mobiltest-de-depistage-salivaire-sur-le-parvis-de-la-gare-saint-la", "/communiques-de-presse"],
  ["en-partenariat-avec-sncf-garesconnexions-et-la-ville-de-nice-doxamed-installe-une-box-de-vaccination-contre-la-covid-19-sur-le-parvis-de-la-gare-de-nice-ville", "/communiques-de-presse"],
  ["la-covid-19-a-fait-naitre-une-solution-medicale-mobile-et-adaptee-aux-deserts-medicaux", "/communiques-de-presse"],
  ["loxamed-sagrandit-et-se-structure-pour-repondre-aux-nouveaux-defis-sanitaires", "/communiques-de-presse"],
  ["la-mairie-de-letang-la-ville-en-partenariat-avec-la-region-ile-de-france-et-doxamed-installe-une-box-mobiltest-de-depistage-de-la-covid-19", "/communiques-de-presse"],
  ["loxamed-installe-des-boxs-mobiltest-de-depistage-du-covid-19-sur-cinq-parvis-de-gares", "/communiques-de-presse"],
  ["doxamed-installe-la-premiere-unite-de-diagnostic-et-de-depistage-embarquee-a-bord-du-train-we-love-2023", "/communiques-de-presse"],
  ["doxamed-deploie-de-deux-camions-itinerants-de-depistage-mobiltests-qui-sillonneront-tout-le-territoire-francilien", "/communiques-de-presse"],
  ["covid-19-lagence-regionale-de-sante-ile-de-france-valide-le-protocole-sanitaire-de-loxamed", "/communiques-de-presse"],
  ["lol-presente-son-retour-a-lactivite-et-le-dispositif-ol-protege", "/communiques-de-presse"],
  ["covid-19-un-pilote-dunites-mobiles-de-diagnostic-et-de-depistage-voit-le-jour-a-paris-dans-le-19eme-pour-accompagner-la-phase-de-deconfinement", "/communiques-de-presse"],
  ["nomination-darnaud-molinie-au-board-france-delectrip", "/dans-les-medias"],
  ["pourquoi-la-creation-de-300-centres-de-telemedecine-dans-les-gares-sncf-a-deraille", "/dans-les-medias"],
  ["leclairage-artistique-de-larc-de-triomphe-sort-enfin-de-lombre", "/dans-les-medias"],
  ["plan-de-sante-bpifrance-interview-darnaud-molinie-et-de-christelle-roge", "/dans-les-medias"],
  ["plan-de-sante-bpifrance-interview-de-christelle-roge", "/dans-les-medias"],
  ["prevention-sante-le-groupe-adp-met-en-place-un-dispositif-inedit-sur-ses-plateformes", "/dans-les-medias"],
  ["acquisition-de-teledok", "/dans-les-medias"],
  ["la-sante-arrive-dans-les-gares-dile-de-france-2", "/dans-les-medias"],
  ["le-groupe-adp-propose-un-bilan-de-sante-complet-a-tous-ses-salaries", "/dans-les-medias"],
  ["ces-soignants-qui-vont-au-devant-des-patients", "/dans-les-medias"],
  ["la-sante-arrive-dans-les-gares-dile-de-france", "/dans-les-medias"],
  ["sncf-la-telemedecine-sinvite-dans-la-gare-journal-de-8h", "/dans-les-medias"],
  ["sncf-la-telemedecine-sinvite-dans-la-gare", "/dans-les-medias"],
  ["deserts-medicaux-la-sncf-transforme-ses-gares-en-cabinets-de-teleconsultation", "/dans-les-medias"],
  ["en-france-la-telemedecine-tente-de-pallier-le-manque-de-medecins-generalistes", "/dans-les-medias"],
  ["teleconsultations-dans-les-gares", "/dans-les-medias"],
  ["le-journal-de-7h-teleconsulter-dans-une-gare-cest-possible", "/dans-les-medias"],
  ["sauve-par-une-infirmiere-grace-a-une-teleconsultation-en-gare", "/dans-les-medias"],
  ["epinay-sur-orge-yann-sauve-par-une-infirmiere", "/dans-les-medias"],
  ["le-journal-de-13h-un-patient-sauve-dans-lespace-de-sante-en-gare-depinay-sur-orge", "/dans-les-medias"],
  ["teleconsulter-un-medecin-dans-une-gare-sncf-cest-desormais-possible", "/dans-les-medias"],
  ["le-premier-centre-de-telemedecine-est-entre-en-gare-sncf", "/dans-les-medias"],
  ["salon-medintech-la-medecine-mobile-innove", "/dans-les-medias"],
  ["la-prevention-sante-une-priorite-pour-la-nation-et-un-nouveau-rolepour-lentreprise", "/dans-les-medias"],
  ["le-business-utile-de-la-telemedecine", "/dans-les-medias"],
  ["retour-au-bureau-lere-du-tout-teletravail-touche-t-elle-a-sa-fin", "/dans-les-medias"],
  ["arnaud-molinie-elu-a-la-presidence-du-fonds-de-dotation-de-paris", "/dans-les-medias"],
  ["un-cabinet-mobile-pour-faire-face-aux-deserts-medicaux", "/dans-les-medias"],
  ["la-matinale-salon-viva-tech-2024-un-camion-novateur-contre-les-deserts-medicaux", "/dans-les-medias"],
  ["teleconsultation-dans-les-gares-la-reponse-aux-deserts-medicaux-qui-fait-tousser-les-medecins-de-ville", "/dans-les-medias"],
  ["la-sncf-va-deployer-des-cabines-de-teleconsultation-dans-pres-de-300-gares", "/dans-les-medias"],
  ["teleconsultation-dans-les-gares-la-nouvelle-sante-de-proximite", "/dans-les-medias"],
  ["deserts-medicaux-la-sncf-va-installer-des-espaces-de-telemedecine", "/dans-les-medias"],
  ["arnaud-molinie-generation-bollore", "/dans-les-medias"],
  ["arnaud-molinie-lhomme-de-faire", "/dans-les-medias"],
  ["avranches-experimente-la-teleconsultation-accompagnee-jusquau-31-aout", "/dans-les-medias"],
  ["sante-avranches-teste-la-consultation-a-distance", "/dans-les-medias"],
  ["lagardere-ne-meurt-jamais", "/dans-les-medias"],
  ["loxam-la-reussite-dune-saga-a-la-francaise", "/dans-les-medias"],
  ["les-decideurs-arnaud-molinie-et-doxamed-loxamed", "/dans-les-medias"],
  ["disneyland-felicite-pour-sa-gestionde-la-crise-sanitaire", "/dans-les-medias"],
  ["depistez-vous-avant-dentrer-en-piste", "/dans-les-medias"],
  ["a-roissy-un-test-pcr-juste-avant-le-decollage", "/dans-les-medias"],
  ["arnaud-molinie-entrepreneur-ultra-mobile", "/dans-les-medias"],
  ["doxamed-loxamed-arnaud-molinie-ou-le-gout-du-defi", "/dans-les-medias"],
  ["doxamed-loxamed-la-securite-covid-du-tournoi-en-france", "/dans-les-medias"],
  ["loxamed-recycle-les-modules-de-chantier-en-unites-covid", "/dans-les-medias"],
  ["tests-les-raisons-dun-retard-sans-fin", "/dans-les-medias"],
  ["deconfinement-des-entreprises-innovent-pour-identifier-et-depister-les-malades", "/dans-les-medias"],
  ["la-sante-mobile-qui-vient-au-coeur-de-lentreprise-va-etre-cruciale-pour-reussir-le-deconfinement-arnaud-molinie", "/dans-les-medias"],
  ["groupe-renault-creates-renault-mai-for-new-mobility-solutions", "/dans-les-medias"],
  ["mobilite-partagee-renault-passe-de-lexperimentation-a-lindustrialisation", "/dans-les-medias"],
  ["renault-crea-m-a-i-per-accelerare-le-nuove-mobilita", "/dans-les-medias"],
  ["renault-agrupa-sus-servicios-de-movilidad-en-renault-mobility-as-a-industry", "/dans-les-medias"],
  ["renault-cree-une-filiale-dediee-aux-nouvelles-formes-de-mobilites", "/dans-les-medias"],
  ["renault-cree-une-filiale-dactivite-dediee-aux-nouvelles-mobilites", "/dans-les-medias"],
  ["arnaud-molinie-la-mobilite-sera-au-coeur-de-toute-leconomie", "/dans-les-medias"],
  ["sncf-sallie-a-renault-pour-lancer-un-nouveau-service-de-chauffeurs", "/dans-les-medias"],
  ["inauguration-du-paris-saclay-autonomous-lab", "/dans-les-medias"],
  ["nomination-darnaud-molinie-chez-renault", "/dans-les-medias"],
  ["nomination-arnaud-molinie", "/dans-les-medias"],
  ["arnaud-molinie-devient-directeur-de-la-communication-et-de-la-marque-de-deloitte-france-et-afrique-francophone", "/dans-les-medias"],
  ["nomination-deloitte", "/dans-les-medias"],
  ["emma-peut-etre-8", "/dans-les-medias"],
  ["emma-peut-etre", "/dans-les-medias"],
  ["parution-emma-peut-etre", "/dans-les-medias"],
  ["emma-peut-etre-7", "/dans-les-medias"],
  ["emma-peut-etre-9", "/dans-les-medias"],
  ["emma-peut-etre-2", "/dans-les-medias"],
  ["emma-peut-etre-4", "/dans-les-medias"],
  ["emma-peut-etre-5", "/dans-les-medias"],
  ["emma-peut-etre-3", "/dans-les-medias"],
  ["emma-peut-etre-6", "/dans-les-medias"],
  ["le-buzz-arnaud-molinie", "/dans-les-medias"],
  ["quas-tu-fait-de-cet-amour", "/dans-les-medias"],
  ["quas-tu-fait-de-cet-amour-2", "/dans-les-medias"],
  ["lagardere-veut-doper-le-paf", "/dans-les-medias"],
  ["culture-match-radio", "/dans-les-medias"],
  ["arnaud-molinie-lagardere-boy-il-entre-dans-la-cour-des-grands", "/dans-les-medias"],
  ["un-lagardere-boy-nouvelle-generation", "/dans-les-medias"],
  ["les-trentenaires-generation-et-moi-et-moi", "/dans-les-medias"],
  ["jo-paris-2012-un-challenge-olympique-pour-les-entreprises", "/dans-les-medias"],
  ["nomination-arnaud-molinie-directeur-delegue-de-lagardere", "/dans-les-medias"],
  ["5e-edition-des-voix-du-telethon", "/dans-les-medias"],
  ["bilan-du-15e-telethon-resultats-en-hausse", "/dans-les-medias"],
  ["telethon-lafm-remercie", "/dans-les-medias"],
  ["lionel-jospin-au-milia", "/dans-les-medias"],
  ["telethon-merci-et-continuez", "/dans-les-medias"],
  ["trois-questions-a-arnaud-molinie", "/dans-les-medias"],
  ["le-telethon-exception-heureuse-dans-le-paysage-de-la-recherche", "/dans-les-medias"],
]

export const LEGACY_POST_REDIRECTS = [
  ...POSTS.map(([slug, destination]) => ({ source: `/${slug}`, destination, permanent: true })),
  { source: '/category/communique-de-presse', destination: '/communiques-de-presse', permanent: true },
  { source: '/category/dans-les-medias', destination: '/dans-les-medias', permanent: true },
  { source: '/tag/:slug', destination: '/communiques-de-presse', permanent: true },
  { source: '/author/:slug', destination: '/', permanent: true },
  { source: '/wp-sitemap.xml', destination: '/sitemap.xml', permanent: true },
]
